### PR TITLE
fix: ignore cgo files

### LINKED ISSUE #162: False positive - cgo - block starting/ending with whitespaces
For the newest wsl (v4.5.0), given this code snippet: 
```go
// SetEventAlarm updates the EventAlarm settings.
func (e *Ecopoint) SetEventAlarm(alarm EventAlarm) error {
	ret := C.ecopointSetEventAlarm(
		e.instance,
		C.uint8_t(alarm.Count), C.uint8_t(alarm.BaseTime), C.uint8_t(alarm.LockTime), C.uint16_t(alarm.Threshold),
	)
	if ret != 0 {
		return getLastError()
	}

	return nil
}
```

I'm getting the following false positives:
```
ecopoint_clib.go:117:27: block should not start with a whitespace
ecopoint_clib.go:120:68: block should not end with a whitespace (or comment)
```

Pointing to the start and end of the `ret` block. 

I'm still trying to isolate the issue, but I've not been able to produce it yet outside of our project.

### PR DESCRIPTION
**Pull request by ldez**
Reverts #159, #157

the cgo support is dropped, but the tests are kept to avoid regression.

Fixes #162

### CODE REVIEW

File: analyzer.go [hunk 1]
```diff
@@ -86,9 +86,13 @@ func (wa *wslAnalyzer) run(pass *analysis.Pass) (interface{}, error) {
 			continue
 		}
 
-		// if the file is related to cgo the filename of the unadjusted position is a not a '.go' file.
 		fn := pass.Fset.PositionFor(file.Pos(), false).Filename
 
+		// if the file is related to cgo the filename of the unadjusted position is a not a '.go' file.
+		if !strings.HasSuffix(fn, ".go") {
+			continue
+		}
```
Comment (bombsimon) [inline analyzer.go:94]: Maybe we can just return `pass.Fset.PositionFor(file.Pos(), false).Filename` from `getFilename`, or even drop `getFilename` and just do this once? I don't think there's any need for first calling `getFilename` to get potential adjusted position/file and then again here to skip it.

Comment (ldez) [reply analyzer.go:94]: if we do that, the `line` directive will not work.
